/**
 * This file was generated by the Jeddict
 */
package entity.domain;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;

/**
 * @author sawad
 */
@Entity
public class Appointment implements Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @Basic
    private String name;

    @Basic
    private String phone;

    @Basic
    private String email;

    @Basic
    private String gender;

    @Basic
    private String DOB;

    @Basic
    private String description;

    @Basic
    private String preferredDoctorGender;

    @Basic
    private String morningOrEvening;

    @ManyToOne
    private Hospital hospital;

    @ManyToMany
    private List<DaysOfWeek> daysOfWeeks;

    public Appointment() {
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPhone() {
        return this.phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getGender() {
        return this.gender;
    }

    public void setGender(String gender) {
        this.gender = gender;
    }

    public String getDOB() {
        return this.DOB;
    }

    public void setDOB(String DOB) {
        this.DOB = DOB;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getPreferredDoctorGender() {
        return this.preferredDoctorGender;
    }

    public void setPreferredDoctorGender(String preferredDoctorGender) {
        this.preferredDoctorGender = preferredDoctorGender;
    }

    public String getMorningOrEvening() {
        return this.morningOrEvening;
    }

    public void setMorningOrEvening(String morningOrEvening) {
        this.morningOrEvening = morningOrEvening;
    }

    public Hospital getHospital() {
        return this.hospital;
    }

    public void setHospital(Hospital hospital) {
        this.hospital = hospital;
    }

    public List<DaysOfWeek> getDaysOfWeeks() {
        if (daysOfWeeks == null) {
            daysOfWeeks = new ArrayList<>();
        }
        return this.daysOfWeeks;
    }

    public void setDaysOfWeeks(List<DaysOfWeek> daysOfWeeks) {
        this.daysOfWeeks = daysOfWeeks;
    }

    public void addDaysOfWeek(DaysOfWeek daysOfWeek) {
        getDaysOfWeeks().add(daysOfWeek);
    }

    public void removeDaysOfWeek(DaysOfWeek daysOfWeek) {
        getDaysOfWeeks().remove(daysOfWeek);
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 53 * hash + Objects.hashCode(this.id);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Appointment other = (Appointment) obj;
        if (!Objects.equals(this.id, other.id)) {
            return false;
        }
        return true;
    }

}