/**
 * This file was generated by the Jeddict
 */
package entity.domain;

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;

/**
 * @author sawad
 */
@Entity
public class Area {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @Basic
    private String name;

    @OneToMany(mappedBy = "area")
    private List<Hospital> hospitals;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public List<Hospital> getHospitals() {
        if (hospitals == null) {
            hospitals = new ArrayList<>();
        }
        return this.hospitals;
    }

    public void setHospitals(List<Hospital> hospitals) {
        this.hospitals = hospitals;
    }

    public void addHospital(Hospital hospital) {
        getHospitals().add(hospital);
        hospital.setArea(this);
    }

    public void removeHospital(Hospital hospital) {
        getHospitals().remove(hospital);
        hospital.setArea(null);
    }

}