/**
 * This file was generated by the Jeddict
 */
package entity.domain;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;

/**
 * @author sawad
 */
@Entity
public class Clinic implements Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @Basic
    private String name;

    @OneToMany(mappedBy = "clinic")
    private List<Doctor> doctors;

    @OneToMany(mappedBy = "clinic")
    private List<ClinicServicePrice> clinicServicePrices;

    @ManyToMany(mappedBy = "clinics")
    private List<Hospital> hospitals;

    public Clinic() {
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public List<Doctor> getDoctors() {
        if (doctors == null) {
            doctors = new ArrayList<>();
        }
        return this.doctors;
    }

    public void setDoctors(List<Doctor> doctors) {
        this.doctors = doctors;
    }

    public void addDoctor(Doctor doctor) {
        getDoctors().add(doctor);
        doctor.setClinic(this);
    }

    public void removeDoctor(Doctor doctor) {
        getDoctors().remove(doctor);
        doctor.setClinic(null);
    }

    public List<ClinicServicePrice> getClinicServicePrices() {
        if (clinicServicePrices == null) {
            clinicServicePrices = new ArrayList<>();
        }
        return this.clinicServicePrices;
    }

    public void setClinicServicePrices(List<ClinicServicePrice> clinicServicePrices) {
        this.clinicServicePrices = clinicServicePrices;
    }

    public void addClinicServicePrice(ClinicServicePrice clinicServicePrice) {
        getClinicServicePrices().add(clinicServicePrice);
        clinicServicePrice.setClinic(this);
    }

    public void removeClinicServicePrice(ClinicServicePrice clinicServicePrice) {
        getClinicServicePrices().remove(clinicServicePrice);
        clinicServicePrice.setClinic(null);
    }

    public List<Hospital> getHospitals() {
        if (hospitals == null) {
            hospitals = new ArrayList<>();
        }
        return this.hospitals;
    }

    public void setHospitals(List<Hospital> hospitals) {
        this.hospitals = hospitals;
    }

    public void addHospital(Hospital hospital) {
        getHospitals().add(hospital);
    }

    public void removeHospital(Hospital hospital) {
        getHospitals().remove(hospital);
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 53 * hash + Objects.hashCode(this.id);
        hash = 53 * hash + Objects.hashCode(this.name);
        hash = 53 * hash + Objects.hashCode(this.doctors);
        hash = 53 * hash + Objects.hashCode(this.clinicServicePrices);
        hash = 53 * hash + Objects.hashCode(this.hospitals);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Clinic other = (Clinic) obj;
        if (!Objects.equals(this.name, other.name)) {
            return false;
        }
        if (!Objects.equals(this.id, other.id)) {
            return false;
        }
        if (!Objects.equals(this.doctors, other.doctors)) {
            return false;
        }
        if (!Objects.equals(this.clinicServicePrices, other.clinicServicePrices)) {
            return false;
        }
        if (!Objects.equals(this.hospitals, other.hospitals)) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return name;
    }

    
}