/**
 * This file was generated by the Jeddict
 */
package entity.domain;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;

/**
 * @author sawad
 */
@Entity
public class Hospital implements Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @Basic
    private String name;

    @Basic
    private String image;

    @Basic
    private String phoneNo;

    @Basic
    private String email;

    @Basic
    private String locationMap;

    @Basic
    private String workingDaysHours;

    @ManyToOne
    private Area area;

    @OneToMany(mappedBy = "hospital")
    private List<ClinicServicePrice> clinicServicePrices;

    @ManyToMany
    private List<Clinic> clinics;

    @ManyToMany(mappedBy = "hospitals")
    private List<Insurance> insurances;

    public Hospital() {
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getImage() {
        return this.image;
    }

    public void setImage(String image) {
        this.image = image;
    }

    public String getPhoneNo() {
        return this.phoneNo;
    }

    public void setPhoneNo(String phoneNo) {
        this.phoneNo = phoneNo;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getLocationMap() {
        return this.locationMap;
    }

    public void setLocationMap(String locationMap) {
        this.locationMap = locationMap;
    }

    public String getWorkingDaysHours() {
        return this.workingDaysHours;
    }

    public void setWorkingDaysHours(String workingDaysHours) {
        this.workingDaysHours = workingDaysHours;
    }

    public Area getArea() {
        return this.area;
    }

    public void setArea(Area area) {
        this.area = area;
    }

    public List<ClinicServicePrice> getClinicServicePrices() {
        if (clinicServicePrices == null) {
            clinicServicePrices = new ArrayList<>();
        }
        return this.clinicServicePrices;
    }

    public void setClinicServicePrices(List<ClinicServicePrice> clinicServicePrices) {
        this.clinicServicePrices = clinicServicePrices;
    }

    public void addClinicServicePrice(ClinicServicePrice clinicServicePrice) {
        getClinicServicePrices().add(clinicServicePrice);
        clinicServicePrice.setHospital(this);
    }

    public void removeClinicServicePrice(ClinicServicePrice clinicServicePrice) {
        getClinicServicePrices().remove(clinicServicePrice);
        clinicServicePrice.setHospital(null);
    }

    public List<Clinic> getClinics() {
        if (clinics == null) {
            clinics = new ArrayList<>();
        }
        return this.clinics;
    }

    public void setClinics(List<Clinic> clinics) {
        this.clinics = clinics;
    }

    public void addClinic(Clinic clinic) {
        getClinics().add(clinic);
        clinic.getHospitals().add(this);
    }

    public void removeClinic(Clinic clinic) {
        getClinics().remove(clinic);
        clinic.getHospitals().remove(this);
    }

    public List<Insurance> getInsurances() {
        if (insurances == null) {
            insurances = new ArrayList<>();
        }
        return this.insurances;
    }

    public void setInsurances(List<Insurance> insurances) {
        this.insurances = insurances;
    }

    public void addInsurance(Insurance insurance) {
        getInsurances().add(insurance);
    }

    public void removeInsurance(Insurance insurance) {
        getInsurances().remove(insurance);
    }

    @Override
    public int hashCode() {
        int hash = 5;
        hash = 17 * hash + Objects.hashCode(this.id);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Hospital other = (Hospital) obj;
        if (!Objects.equals(this.id, other.id)) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return name + ", " + area;
    }

}
